/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class gcmServer_jni_run */

#ifndef _Included_gcmServer_App
#define _Included_gcmServer_App
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     gcmServer_jni_run
     * Method:    print
     * Signature: ()V
     */
    JNIEXPORT void JNICALL Java_gcmServer_App_visionCap
    (JNIEnv *, jobject);
    
    JNIEXPORT jstring JNICALL Java_gcmServer_App_signal
    (JNIEnv *, jobject, jstring);
    
    JNIEXPORT jbyteArray JNICALL Java_gcmServer_App_frameObtain
    (JNIEnv *, jobject);
    
#ifdef __cplusplus
}
#endif
#endif
